import React from 'react';
import './ReportTemplate.css';

// สีประจำแต่ละคลาสรอยโรค (ตรงกับ Backend)
const LESION_COLORS = {
  OpticDisc:    '#0000FF',
  Macula:       '#00FF00',
  Exudates:     '#FFFF00',
  Hemorrhages:  '#FF0000',
  Drusen:       '#00FFFF',
};

const ReportTemplate = ({ patientId, eyeLaterality, lesions, severity, confidence, imageBase64, maskBase64 }) => {

  const now = new Date();
  const dateStr = now.toLocaleDateString('en-GB');
  const timeStr = now.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' });

  // Calculate Total Lesions directly from lesions array
  const totalLesionCount = lesions?.reduce((acc, l) => acc + (l.count || 0), 0) || 0;

  return (
    <div id="pdf-report-content" className="report-container">

      {/* ========== 1. HEADER ========== */}
      <div className="report-header">
        <div className="header-left">
          <h1 className="brand-title">
            <span className="brand-jaksu">Jaksu</span>
            <span className="brand-health">Health</span>
          </h1>
          <p className="brand-subtitle">Retinal Fundus Analysis Report</p>
        </div>
        <div className="header-right">
          <p>Date : {dateStr}</p>
          <p>Time: {timeStr}</p>
        </div>
      </div>

      {/* ========== 2. CLINICAL INFORMATION ========== */}
      <div className="section-container">
        <h3 className="section-title">CLINICAL INFORMATION</h3>
        <div className="info-grid">
          <div className="info-box">
            <span className="info-label">PATIENT ID</span>
            <p className="info-value">{patientId || 'N/A'}</p>
          </div>
          <div className="info-box">
            <span className="info-label">EYE LATERALITY</span>
            <p className="info-value">{eyeLaterality || 'N/A'}</p>
          </div>
        </div>
      </div>

      {/* ========== 3. BIOMARKER VISUALISATION ========== */}
      <div className="section-container">
        <h3 className="section-title">BIOMARKER VISUALISATION</h3>
        <div className="image-wrapper">
          {imageBase64 && (
            <img src={imageBase64} alt="Fundus Original" className="base-image" />
          )}
          {maskBase64 && (
            <img
              src={`data:image/png;base64,${maskBase64}`}
              alt="AI Mask Overlay"
              className="overlay-image"
            />
          )}
        </div>
      </div>

      {/* ========== 4. ANALYSIS METRICS ========== */}
      <div className="section-container">
        <h3 className="section-title">ANALYSIS METRICS</h3>

        {/* Metrics Summary (3 กล่อง) */}
        <div className="metrics-summary">
          <div className="metric-item">
            <span className="metric-label">Confidence</span>
            <span className="metric-value highlight-orange">{confidence}%</span>
          </div>
          <div className="metric-item">
            <span className="metric-label">Total lesion</span>
            <span className="metric-value">{totalLesionCount}</span>
          </div>
          <div className="metric-item">
            <span className="metric-label">Severity Level</span>
            <span className="metric-value-text">{severity}</span>
          </div>
        </div>

        {/* Lesion Detail Table */}
        <table className="analysis-table">
          <thead>
            <tr>
              <th>LESION TYPE</th>
              <th>COUNT</th>
              <th>AREA PERCENTAGE</th>
              <th>MAX (MM)</th>
              <th>STATUS</th>
            </tr>
          </thead>
          <tbody>
            {lesions && lesions.length > 0 ? (
              lesions.map((lesion, index) => (
                <tr key={index}>
                  <td className="disease-cell">
                    <span
                      className="color-box"
                      style={{ backgroundColor: lesion.color || LESION_COLORS[lesion.type] || '#999' }}
                    ></span>
                    {lesion.type}
                  </td>
                  <td>{lesion.count}</td>
                  <td>{lesion.area_percentage}</td>
                  <td>{lesion.max_mm}</td>
                  <td>{lesion.status}</td>
                </tr>
              ))
            ) : (
              <tr>
                <td colSpan="5" style={{ textAlign: 'center' }}>No lesions found</td>
              </tr>
            )}
          </tbody>
        </table>
      </div>

      {/* ========== 5. FOOTER ========== */}
      <div className="report-footer">
        <p>This report is generated by JaksuHealth AI System. For clinical reference only</p>
      </div>

    </div>
  );
};

export default ReportTemplate;
