import React from 'react';
import './ReportTemplate.css';

// สีประจำแต่ละคลาสรอยโรค (ตรงกับ Backend)
const LESION_COLORS = {
  OpticDisc:    '#0000FF',
  Macula:       '#00FF00',
  Exudates:     '#FFFF00',
  Hemorrhages:  '#FF0000',
  Drusen:       '#00FFFF',
};

const ReportTemplate = ({ patientId, eyeLaterality, findings, imageBase64, maskBase64 }) => {

  const now = new Date();
  const dateStr = now.toLocaleDateString('en-GB');
  const timeStr = now.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' });

  // TODO: คำนวณ Total Lesion (ตอนนี้นับจากจำนวนคลาสที่เจอ)
  const totalLesionTypes = Object.keys(findings).length;

  // TODO: คำนวณ Severity Level จากจำนวนรอยโรคหรือพิกเซลรวม
  // Logic: กำหนดเกณฑ์เอง เช่น 1 คลาส = Mild, 2-3 = Intermediate, 4+ = Severe
  const severityLevel = 'Intermediate';

  // TODO: คำนวณ Confidence (ถ้า Backend ยังไม่ส่งมา ใส่ Mock ไว้ก่อน)
  const confidence = 94;

  return (
    <div id="pdf-report-content" className="report-container">

      {/* ========== 1. HEADER ========== */}
      <div className="report-header">
        <div className="header-left">
          <h1 className="brand-title">
            <span className="brand-jaksu">Jaksu</span>
            <span className="brand-health">Health</span>
          </h1>
          <p className="brand-subtitle">Retinal Fundus Analysis Report</p>
        </div>
        <div className="header-right">
          <p>Date : {dateStr}</p>
          <p>Time: {timeStr}</p>
        </div>
      </div>

      {/* ========== 2. CLINICAL INFORMATION ========== */}
      <div className="section-container">
        <h3 className="section-title">CLINICAL INFORMATION</h3>
        <div className="info-grid">
          <div className="info-box">
            <span className="info-label">PATIENT ID</span>
            <p className="info-value">{patientId || 'N/A'}</p>
          </div>
          <div className="info-box">
            <span className="info-label">EYE LATERALITY</span>
            <p className="info-value">{eyeLaterality || 'N/A'}</p>
          </div>
        </div>
      </div>

      {/* ========== 3. BIOMARKER VISUALISATION ========== */}
      <div className="section-container">
        <h3 className="section-title">BIOMARKER VISUALISATION</h3>
        <div className="image-wrapper">
          {imageBase64 && (
            <img src={imageBase64} alt="Fundus Original" className="base-image" />
          )}
          {maskBase64 && (
            <img
              src={`data:image/png;base64,${maskBase64}`}
              alt="AI Mask Overlay"
              className="overlay-image"
            />
          )}
        </div>
      </div>

      {/* ========== 4. ANALYSIS METRICS ========== */}
      <div className="section-container">
        <h3 className="section-title">ANALYSIS METRICS</h3>

        {/* Metrics Summary (3 กล่อง) */}
        <div className="metrics-summary">
          <div className="metric-item">
            <span className="metric-label">Confidence</span>
            <span className="metric-value highlight-orange">{confidence}%</span>
          </div>
          <div className="metric-item">
            <span className="metric-label">Total lesion</span>
            <span className="metric-value">{totalLesionTypes}</span>
          </div>
          <div className="metric-item">
            <span className="metric-label">Severity Level</span>
            <span className="metric-value-text">{severityLevel}</span>
          </div>
        </div>

        {/* Lesion Detail Table */}
        <table className="analysis-table">
          <thead>
            <tr>
              <th>LESION TYPE</th>
              <th>COUNT</th>
              <th>AREA PERCENTAGE</th>
              <th>MAX (MM)</th>
              <th>STATUS</th>
            </tr>
          </thead>
          <tbody>
            {Object.entries(findings).map(([diseaseName, pixelCount], index) => (
              <tr key={index}>
                <td className="disease-cell">
                  <span
                    className="color-box"
                    style={{ backgroundColor: LESION_COLORS[diseaseName] || '#999' }}
                  ></span>
                  {diseaseName}
                </td>
                <td>{pixelCount}</td>
                {/* TODO: คำนวณ Area Percentage = (pixelCount / totalPixels) * 100 */}
                <td>-</td>
                {/* TODO: คำนวณ Max (mm) ขนาดจุดที่ใหญ่ที่สุด */}
                <td>-</td>
                <td>{pixelCount > 1000 ? 'Significant' : 'Moderate'}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* ========== 5. FOOTER ========== */}
      <div className="report-footer">
        <p>This report is generated by JaksuHealth AI System. For clinical reference only</p>
      </div>

    </div>
  );
};

export default ReportTemplate;
